#!/usr/bin/env python3
"""Generate the deterministic WorkspacePath corpus for the S1 regression fence.

Same generator and seed as falsify-normalization.py (20260802). Each corpus
entry's expectation is recorded from the realpath -m oracle (independent of
the Rust implementation); policy rejections (control chars, whitespace-only)
have no realpath counterpart and live in a separate array.
"""
import json
import os
import random
import subprocess

ROOT = "/home/dwalleck/repos/rivets"
random.seed(20260802)

COMPONENTS = [
    "src", "lib.rs", "docs", "a b", "é", "文件.md", ".hidden", "x.y.z",
    "a-b_c", "deep", "..", ".", "", "dir:", "C:", "with space",
]

def oracle(raw: str) -> str | None:
    out = subprocess.run(
        ["realpath", "-m", os.path.join(ROOT, raw)],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    if out == ROOT or not out.startswith(ROOT + "/"):
        return None
    return out[len(ROOT) + 1:]

cases = set()
for _ in range(400):
    n = random.randint(1, 5)
    cases.add("/".join(random.choice(COMPONENTS) for _ in range(n)))
for _ in range(100):
    cases.add("/" + random.choice(COMPONENTS))
for _ in range(100):
    cases.add("../" + "/".join(random.choice(COMPONENTS) for _ in range(3)))

def rust_str(value: str) -> str:
    # json escaping is close to Rust's; convert \uXXXX to \u{XXXX}.
    import re
    return re.sub(r"\\u([0-9a-fA-F]{4})", r"\\u{\1}", json.dumps(value, ensure_ascii=False))


def rust_lit(value: str | None) -> str:
    if value is None:
        return "None"
    return "Some(" + rust_str(value) + ")"


corpus = sorted((c, oracle(c)) for c in cases)
lines = [
    "// Generated by .rivets-p1g4/gen-corpus.py (seed 20260802).",
    "// Expectations recorded from the realpath -m oracle; do not hand-edit.",
    "#[cfg(test)]",
    "pub(super) const CORPUS: &[(&str, Option<&str>)] = &[",
]
for raw, want in corpus:
    lines.append(f'    ({rust_str(raw)}, {rust_lit(want)}),')
lines.append("];")
lines.append("")
lines.append("#[cfg(test)]")
lines.append('/// Policy rejections realpath cannot express (legal filenames, rejected by domain policy).')
lines.append('pub(super) const POLICY_REJECT: &[&str] = &["   "];')
print("\n".join(lines))