#!/usr/bin/env python3
"""Render the CLI/MCP Interface Parity reference from its JSON registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "docs" / "cli-mcp-parity.json"
OUTPUT_PATH = ROOT / "docs" / "cli-mcp-parity.md"


def markdown(value: object) -> str:
    """Escape one value for a Markdown table cell."""
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def surfaces(adapter: dict[str, Any]) -> str:
    """Render current adapter surfaces, including non-leaf forms."""
    values = [f"`{value}`" for value in adapter.get("surfaces", [])]
    values.extend(
        f"`{form['surface']} --{form['argument']}`"
        for form in adapter.get("forms", [])
    )
    return ", ".join(values) if values else "—"


def arguments(adapter: dict[str, Any]) -> str:
    """Render an adapter's argument mapping."""
    values = adapter.get("arguments", {})
    if not values:
        return "—"
    return "; ".join(f"`{name}`: {contract}" for name, contract in values.items())


def render(registry: dict[str, Any]) -> str:
    """Render the complete Markdown reference deterministically."""
    operations = registry["operations"]
    decision = registry["decision"]
    cli_leaves = sorted(
        {surface for operation in operations for surface in operation["cli"].get("surfaces", [])}
    )
    mcp_tools = sorted(
        {surface for operation in operations for surface in operation["mcp"].get("surfaces", [])}
    )
    shared = sum(
        bool(operation["cli"].get("surfaces") or operation["cli"].get("forms"))
        and bool(operation["mcp"].get("surfaces"))
        for operation in operations
    )

    lines = [
        "# CLI and MCP Interface Parity",
        "",
        "<!-- Generated by scripts/render-cli-mcp-parity.py from cli-mcp-parity.json. -->",
        "",
        "This reference is rendered from the [machine-readable parity registry](./cli-mcp-parity.json). "
        f"The registry is authoritative; [{decision['id']}](./{decision['path']}) records why "
        "Rivets requires semantic rather than syntactic parity.",
        "",
        "## Contract",
        "",
        registry["definition"],
        "",
        f"The current inventory contains **{len(cli_leaves)} CLI leaf operations** and "
        f"**{len(mcp_tools)} MCP tools**. **{shared} domain intents** currently have a surface in both adapters; "
        "this count includes alternate forms such as CLI `update --notes` for MCP `add_note`.",
        "",
        "Interface Parity follows canonical domain language. `status` remains a current code-and-wire field name; "
        "the domain concept is **Workflow State**. Generic dependency operations are legacy; canonical target intents "
        "use Blocking Dependency, Parentage, Related Association, and Discovery Origin.",
        "",
        "## Status legend",
        "",
        "### Current parity",
        "",
        "| Value | Meaning |",
        "|---|---|",
    ]
    for value, meaning in registry["current_parity_values"].items():
        lines.append(f"| `{markdown(value)}` | {markdown(meaning)} |")

    lines.extend(["", "### Target status", "", "| Value | Meaning |", "|---|---|"])
    for value, meaning in registry["target_status_values"].items():
        lines.append(f"| `{markdown(value)}` | {markdown(meaning)} |")

    lines.extend(["", "## Adapter mechanics", ""])
    lines.extend(f"- {item}" for item in registry["adapter_mechanics"])

    lines.extend(
        [
            "",
            "## Required cross-cutting contract",
            "",
            "| Rule | Status | Contract | Evidence |",
            "|---|---|---|---|",
        ]
    )
    for rule in registry["target_rules"]:
        evidence = "; ".join(f"`{markdown(item)}`" for item in rule.get("evidence", [])) or "—"
        lines.append(
            f"| `{markdown(rule['id'])}` | `{markdown(rule.get('status', 'pending'))}` | "
            f"{markdown(rule['contract'])} | {evidence} |"
        )

    lines.extend(
        [
            "",
            "## Operation coverage matrix",
            "",
            "| Intent | Requirement | CLI surface | MCP surface | Current parity | Target status |",
            "|---|---|---|---|---|---|",
        ]
    )
    for operation in operations:
        lines.append(
            "| {title}<br>`{identifier}` | `{requirement}` | {cli} | {mcp} | `{current}` | `{target}` |".format(
                title=markdown(operation["title"]),
                identifier=markdown(operation["id"]),
                requirement=markdown(operation["requirement"]),
                cli=markdown(surfaces(operation["cli"])),
                mcp=markdown(surfaces(operation["mcp"])),
                current=markdown(operation["current_parity"]),
                target=markdown(operation["target_status"]),
            )
        )

    lines.extend(
        [
            "",
            "## Current arguments and required result",
            "",
            "Adapter-only invocation mechanics remain visible here so a reader can distinguish intentional syntax from semantic drift.",
            "",
            "| Intent | CLI arguments | MCP arguments | Required semantic result |",
            "|---|---|---|---|",
        ]
    )
    for operation in operations:
        lines.append(
            "| `{identifier}` | {cli} | {mcp} | {target} |".format(
                identifier=markdown(operation["id"]),
                cli=markdown(arguments(operation["cli"])),
                mcp=markdown(arguments(operation["mcp"])),
                target=markdown(operation["target"]),
            )
        )

    lines.extend(
        [
            "",
            "## Drift and gap matrix",
            "",
            "Rows already conformant to their target are omitted. Risk describes the observable failure mode; required resolution describes the contract change, not a delivery schedule.",
            "",
            "| Intent | Current differences | Risk | Required resolution |",
            "|---|---|---|---|",
        ]
    )
    for operation in operations:
        if operation["target_status"] == "conformant":
            continue
        difference = "; ".join(operation.get("differences", [])) or "—"
        lines.append(
            "| `{identifier}` | {difference} | {risk} | {resolution} |".format(
                identifier=markdown(operation["id"]),
                difference=markdown(difference),
                risk=markdown(operation["risk"]),
                resolution=markdown(operation["required_resolution"]),
            )
        )

    lines.extend(
        [
            "",
            "## Delivery groups",
            "",
            "These consolidated Tasks cover the remaining gaps. Blocking relationships are the tracker source of execution order; one Task may cover several intent rows.",
            "",
            "| Group | Tracking Issue | Intents | Blocked by |",
            "|---|---|---|---|",
        ]
    )
    for group in registry["delivery_groups"]:
        intents = ", ".join(f"`{intent}`" for intent in group["intents"])
        blocked_by = ", ".join(f"`{issue}`" for issue in group["blocked_by"]) or "—"
        lines.append(
            "| {title}<br>`{identifier}` | `{issue}` | {intents} | {blocked_by} |".format(
                title=markdown(group["title"]),
                identifier=markdown(group["id"]),
                issue=markdown(group["tracking_issue"]),
                intents=markdown(intents),
                blocked_by=markdown(blocked_by),
            )
        )

    lines.extend(
        [
            "",
            "## Evidence map",
            "",
            "| Intent | Evidence |",
            "|---|---|",
        ]
    )
    for operation in operations:
        evidence = "; ".join(f"`{item}`" for item in operation.get("evidence", [])) or "—"
        lines.append(f"| `{markdown(operation['id'])}` | {markdown(evidence)} |")

    lines.extend(
        [
            "",
            "## Maintenance",
            "",
            "1. Update `docs/cli-mcp-parity.json` when a CLI leaf, MCP tool, accepted domain decision, observable shared contract, or delivery-group tracker mapping changes.",
            "2. Run `python scripts/render-cli-mcp-parity.py` to regenerate this reference.",
            "3. Run `python scripts/render-cli-mcp-parity.py --check` and the MCP parity registry contract test before committing.",
            "4. Change a gap to `conformant` only after a behavioral test proves the required contract through both adapters.",
            "",
            "The inventory fence classifies surfaces; it does not prove behavioral parity. Behavioral tests remain the proof for defaults, validation, ordering, errors, mutation effects, and result meaning.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Render or check the committed parity reference."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed Markdown differs from the registry",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="write rendered Markdown to stdout instead of the documentation file",
    )
    args = parser.parse_args()

    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    rendered = render(registry)

    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run "
                "python scripts/render-cli-mcp-parity.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Rendered {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
